### ISSUE TITLE
LogUploader failure blocks worker

### ISSUE THREAD

**Issue by laughedelic** [ohnosequences/loquat#55]
Got this:

```
15:55:23.833 [ForkJoinPool-1-worker-1] INFO  ohnosequences.loquat.DataProcessor - Processing data in: /media/ephemeral0/applicator/loquat
Mar 02, 2016 4:04:49 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Remote host closed connection during handshake
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:992)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
...
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3649)
        at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:824)
        at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:760)
        at ohnosequences.awstools.s3.S3.ohnosequences$awstools$s3$S3$$createBucketAction$1(S3.scala:183)
        at ohnosequences.awstools.s3.S3$$anonfun$createBucket$1.apply(S3.scala:190)
        at ohnosequences.awstools.s3.S3$$anonfun$createBucket$1.apply(S3.scala:190)
        at ohnosequences.awstools.s3.S3.tryAction(S3.scala:170)
        at ohnosequences.awstools.s3.S3.createBucket(S3.scala:190)
        at ohnosequences.awstools.s3.S3$$anonfun$uploadFile$1.apply$mcV$sp(S3.scala:265)
        at ohnosequences.awstools.s3.S3$$anonfun$uploadFile$1.apply(S3.scala:264)
        at ohnosequences.awstools.s3.S3$$anonfun$uploadFile$1.apply(S3.scala:264)
        at scala.util.Try$.apply(Try.scala:192)
        at ohnosequences.awstools.s3.S3.uploadFile(S3.scala:264)
        at ohnosequences.loquat.LogUploaderBundle$$anonfun$uploadLog$3.apply(logger.scala:31)
        at ohnosequences.loquat.LogUploaderBundle$$anonfun$uploadLog$3.apply(logger.scala:30)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at ohnosequences.loquat.LogUploaderBundle.uploadLog(logger.scala:30)
        at ohnosequences.loquat.LogUploaderBundle$$anonfun$instructions$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(logger.scala:42)
        at ohnosequences.loquat.utils$Scheduler$$anon$1.run(utils.scala:68)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        ... 46 more
```

after that worker doesn't react.

**Comment by laughedelic** [comment]
I suspect that it was actually related to #56. Also it's about proper exceptions handling in the worker loop.

**Comment by eparejatobes** [comment]
Yes, seems likely
